In [28]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import mutual_info_classif
from sklearn.impute import KNNImputer
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv('./data_public.csv')
df.head()

,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Class
0,231.420023,-12.210984,217.624839,-15.611916,140.047185,76.904999,131.591871,198.160805,82.873279,127.350084,224.592926,-5.992983,-14.689648,143.072058,153.439659,2
1,-38.019270,-14.195695,9.583547,22.293822,-25.578283,-18.373955,-0.094457,-33.711852,-8.356041,23.792402,4.199023,2.809159,-59.330681,-11.685950,1.317104,3
2,-39.197085,-20.418850,21.023083,19.790280,-25.902587,-19.189004,-2.953836,-25.299219,-6.612401,26.285392,5.911292,6.191587,-56.924996,-4.675187,-1.027830,2
3,221.630408,-5.785352,216.725322,-9.900781,126.795177,85.122288,108.857593,197.640135,82.560019,157.105143,212.989231,-3.621070,-15.469156,135.265859,149.212489,2
4,228.558412,-12.447710,204.637218,-13.277704,138.930529,91.101870,115.598954,209.300011,89.961688,130.299732,201.795100,-1.573922,-15.128603,148.368622,147.492663,3

In [30]:
labels = df.columns.tolist()[:-1]
X = pd.DataFrame(data=df.drop('Class', axis=1),
columns=labels)
y = pd.DataFrame(data=df['Class'],
columns=['Class'])
X_train, X_test, y_train, y_test = train_test_split(X,
y,
test_size=0.3)
training_data = pd.concat([X_train,
y_train],
axis=1)
training_data.head()

,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,Class
940456,-33.741735,-12.653404,13.131483,17.391931,-26.626486,-20.958418,6.430341,-18.916781,-3.342468,22.866587,4.168777,3.215168,-55.134724,-7.399474,0.214413,2
900078,-25.738669,-18.621906,16.927298,21.011291,-24.376760,-18.149344,-1.627871,-24.344006,-7.209777,33.740088,7.116195,9.429338,-54.938409,-10.242820,3.203669,3
359397,-31.806756,-12.976394,11.259528,24.809768,-20.763626,-26.466775,0.050658,-29.418819,-6.974794,24.744664,-4.054520,-2.182862,-57.533644,-9.652512,-0.153074,1
271413,217.472440,-7.176711,220.440997,-11.733546,126.210076,87.225839,131.856399,203.561577,86.388159,131.003242,200.983962,1.798314,-23.050121,143.407552,155.171414,2
1110959,-34.820911,-13.224430,15.692035,22.472928,-26.597377,-34.955550,-1.114155,-25.783198,-6.501146,27.076169,5.671547,2.879331,-56.213564,-4.531228,2.899552,2

In [31]:
print(df.isnull().sum())  

num_cols = df.select_dtypes(include='number').columns
imputer_knn = KNNImputer(n_neighbors=5)
df[num_cols] = imputer_knn.fit_transform(df[num_cols])

A        0
B        0
C        0
D        0
E        0
F        0
G        0
H        0
I        0
J        0
K        0
L        0
M        0
N        0
O        0
Class    0
dtype: int64

In [32]:

mi = mutual_info_classif(X, y.values.ravel())
mi_scores = pd.DataFrame({
    '特征': X.columns, 
    '互信息': mi
}).sort_values('互信息', ascending=False)
print(mi_scores)

   特征       互信息
8   I  0.000767
3   D  0.000418
9   J  0.000295
10  K  0.000183
13  N  0.000119
11  L  0.000068
1   B  0.000000
6   G  0.000000
5   F  0.000000
4   E  0.000000
2   C  0.000000
0   A  0.000000
7   H  0.000000
12  M  0.000000
14  O  0.000000